stages:
  - build
  - deploy

image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  script:
    - npm run deploy
