stages:
  - build
  - deploy

image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - npm install -g firebase-tools
  - \cp .fixes/menu.d.ts node_modules/@material-tailwind/react/types/components/menu.d.ts

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - "dist"

deploy:
  stage: deploy
  script:
    - npm run deploy
