# Pipeline for build and deploy the project automatically when pushed to Gitlab
stages:
  - build
  - deploy

image: node:latest

cache:
  paths:
    - node_modules/

# Install dependencies and replaces a file that solves an error in third-party Material Tailwind library
before_script:
  - npm install
  - npm install -g firebase-tools
  - \cp .fixes/menu.d.ts node_modules/@material-tailwind/react/types/components/menu.d.ts

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - "dist"

# Deploy to Firebase hosting service
deploy:
  stage: deploy
  script:
    - npm run deploy
